name: Bug report
description: Create a report to help us improve
labels: ["bug", "triage"]
assignees:
- immersum
body:
- type: markdown
  attributes:
    value: >
      Thanks for taking the time to fill out this bug report! Please make sure to fill
      out the entire form below, providing as much context as you can in order to help
      us triage and track down your bug as quickly as possible.

      Before filing a bug, please be sure you have searched through [existing bugs](
      https://github.com/immersum/mplusfonts/issues?q=is:issue+is:open+sort:updated-desc+label:bug)
      to see if an existing issue covers your bug.

      Before we begin, please make sure that the bug is still present in the [latest](
      https://crates.io/crates/mplusfonts) version of this crate.
- type: dropdown
  id: component
  attributes:
    label: Component(s)
    description: Which component(s) does your bug report concern?
    multiple: true
    options:
    - examples
    - macros/mplus
    - macros/strings
    - BitmapFont
    - BitmapFontStyle
    - BitmapFontStyleBuilder
- type: textarea
  id: what-happened
  attributes:
    label: What did you expect to happen? What actually happened?
    description: Describe the issue here
    value: |
      ## Description

      ## Expected behavior

      ## Actual behavior

  validations:
    required: true
- type: textarea
  id: reproduce
  attributes:
    label: Steps to reproduce
    description: Minimal code to reproduce the issue
    render: rust
- type: input
  id: version
  attributes:
    label: Crate version
    description: What version did you use? (e.g., `v0.1.3`, `72906dc`, etc)
  validations:
    required: true
- type: textarea
  id: environment
  attributes:
    label: Environment information
    description: Additional information about your development environment
    value: |
      ## Environment
      OS: (e.g., "Arch Linux")
      Compiler: (e.g., "rustc 1.86.0")

- type: checkboxes
  attributes:
    label: Checklist
    options:
    - label: >
        I agree to follow the
        [code of conduct](https://github.com/immersum/.github/blob/main/CODE_OF_CONDUCT.md).
      required: true
    - label: >
        I can reproduce the bug with the
        [latest](https://crates.io/crates/mplusfonts) version of this crate.
      required: true
